alter table workflow_run rename to workflow_runs;
alter table workflow_runs rename constraint workflow_run_pkey to workflow_runs_pkey;
alter table workflow_runs rename constraint workflow_run_workflow_id_fkey to workflow_runs_workflow_id_fkey;
alter table workflow_runs rename constraint workflow_run_workspace_id_fkey to workflow_runs_workspace_id_fkey;
alter table workflow_runs rename constraint workflow_run_conversation_id_fkey to workflow_runs_conversation_id_fkey;
alter index idx_workflow_run_conversation rename to idx_workflow_runs_conversation;
alter index idx_workflow_run_workflow rename to idx_workflow_runs_workflow;
alter index idx_workflow_run_workspace rename to idx_workflow_runs_workspace;

alter table workflow_run_step rename to workflow_run_steps;
alter table workflow_run_steps rename constraint workflow_run_step_pkey to workflow_run_steps_pkey;
alter table workflow_run_steps rename constraint workflow_run_step_run_id_fkey to workflow_run_steps_run_id_fkey;
alter index idx_workflow_run_step_run rename to idx_workflow_run_steps_run;

alter table ai_agent_invocation_log rename to ai_agent_invocation_logs;
alter table ai_agent_invocation_logs rename constraint ai_agent_invocation_log_pkey to ai_agent_invocation_logs_pkey;
alter table ai_agent_invocation_logs rename constraint ai_agent_invocation_log_workspace_id_fkey to ai_agent_invocation_logs_workspace_id_fkey;
alter table ai_agent_invocation_logs rename constraint ai_agent_invocation_log_conversation_id_fkey to ai_agent_invocation_logs_conversation_id_fkey;
alter table ai_agent_invocation_logs rename constraint ai_agent_invocation_log_triggered_workflow_run_id_fkey to ai_agent_invocation_logs_triggered_workflow_run_id_fkey;
